# Platform Configuration
platform:
  ios:
    snapshotKeyHonorModalViews: false
    disableAnimations: true
  android:
    disableAnimations: true

# Appium Configuration
appiumConfiguration:
  capabilities:
    platformName: iOS
    udid: F40C4AA5-07D4-46B2-BD02-5DE1871C0FF6
    automationName: XCUITest
    noReset: true
    bundleId: com.getvymo.ios.enterprise
    appium:settings[snapshotMaxDepth]: 60
    appium:settings[pageSourceExcludedAttributes]: "visible,accessible"